apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeguru-python-app-deployment
  labels:
    app: codeguru-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeguru-python-app
  template:
    metadata:
      labels:
        app: codeguru-python-app
    spec:
      serviceAccountName: codeguru-profiler
      containers:
      - name: codeguru-python-app-deployment
        image: 338918620411.dkr.ecr.eu-west-1.amazonaws.com/codeguru-python-app-deployment:latest
